### ISSUE TITLE
Forum : foncer la puce d'un sous-forum sans nouveau message

### ISSUE THREAD

**Issue by ced75** [postgresqlfr/postgresqlfr-theme-v4#6]
Sur le nouveau forum, dans la liste des sous-forums, la puce à gauche d'un sous-forum qui ne possède pas de message nouveau non-lu est trop clair.
Sur un écran avec une résolution et des couleurs moyennes, on ne la voit pratiquement plus.

Voici la puce en question:
![image](https://user-images.githubusercontent.com/12892581/84658379-17b37680-af16-11ea-9f14-5b1367abe69b.png)

**Comment by daamien** [comment]
Bonjour,

J'ai l'impression que c'est volontaire de la part de l'auteur du style original sur lequel on se base. 

Par définition, s'il n'y a pas de messages non-lu, il n'est pas nécessaire d'avertir le visiteur et donc l'icone est quasi-transparente. 

On a le même comportement sur le forum actuel : https://forums.postgresql.fr/

**Comment by daamien** [comment]
Corrigé
