### ISSUE TITLE
Page d'accueil : le bandeau cache le titre de la page

### ISSUE THREAD

**Issue by ced75** [postgresqlfr/postgresqlfr-theme-v4#7]
Le bandeau du haut cache le titre de la page, et les menus ne sont pas bien alignés.
Voici la copie d'écran obtenue avec une résolution 1280 × 1024:
![image](https://user-images.githubusercontent.com/12892581/84658819-bd66e580-af16-11ea-8f62-63e5c49f1226.png)

**Comment by daamien** [comment]
Effectivement je teste essentiellement sur une largeur de 1366....

Il y a clairement un problème pour tous les écrans  entre 750 et 1200 , c'est à dire les tablettes et les petits PC portables...

**Comment by ced75** [comment]
Pour info, le problème se produit avec le navigateur Chrome, mais pas avec Firefox, à résolution identique.
Et sous Chrome, le changement de thème Bootswatch peut aussi résoudre le problème. Par exemple, avec le thème Cerulean, le problème disparaît.

**Comment by daamien** [comment]
A priori j'ai corrigé le problème pour la définition 1280 × 1024

Est-ce que tu peux confirmer ?
